import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const notoSans = Noto_Sans_KR({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSans.className}>
        {children}
        <Toaster
          toastOptions={{
            duration: 1500,
            position: 'bottom-center',
          }}
          containerStyle={{
            bottom: '12.8rem',
          }}
        />
      </body>
    </html>
  );
}
